tables:
  marknadsurval_cupdate:
    #ENGINE: MyISAM
    field:
      id:
        primary_key: true
        type: varchar(50)
        not_null: true
      pid:
        type: varchar(255)
      first_name:
        type: varchar(255)
      given_name:
        type: varchar(255)
      surname:
        type: varchar(255)
      address:
        type: varchar(255)
      zip:
        type: varchar(255)
      city:
        type: varchar(255)
      moved_at:
        type: varchar(255)
      status:
        type: varchar(255)
extra:
  _description: 'Extra field to add to each table if not exist in schema.'
  field:
    created_at:
      type: timestamp
      default: CURRENT_TIMESTAMP
    updated_at:
      type: timestamp
    created_by:
      type: varchar(50)
    updated_by:
      type: varchar(50)
